server:
  port: 8081

spring:
  application:
    name: flight-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

rapidapi:
  flight:
    key: ${RAPIDAPI_KEY}
    host: sky-scrapper.p.rapidapi.com